version: "3.8"
services:
  server:
    build: .
    container_name: server
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: "${NODE_ENV}"
    restart: unless-stopped
    command: npm start
    depends_on:
      - db
  db:
    container_name: media_db
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    # volumes:
    #   - media_data:/var/lib/postgresql/data/
    restart: unless-stopped
networks:
  default:
    name: media-network
volumes:
  media_data:
